#!/usr/bin/env bash
lock() {
    i3lock
}

case "$1" in
    lock)
        $HOME/dotfiles/i3/scripts/lock
        exit 0
        ;;
    logout)
        action() {
          i3-msg exit
        }
        ;;
    suspend)
        action() {
          lock && systemctl suspend
        }
        ;;
    reboot)
        action() {
          systemctl reboot
        }
        ;;
    shutdown)
        action() {
          systemctl poweroff
        }
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

XRES=`cat ~/.Xresources`
get_xres_color() {
    echo `echo "$XRES" | grep "#define $1" | awk '{print \$3}'`
}

C_FOREGROUND=`get_xres_color "base05"`
C_BACKGROUND=`get_xres_color "base00"`
C_RED=`get_xres_color "base08"`

[ `echo -e "NO\nYES" | dmenu -nb "$C_BACKGROUND" -nf "$C_FOREGROUND" -sb "$C_RED" -sf "$C_FOREGROUND" -fn "Terminess Powerline-8" -i -p "Do you really want to $1?"` = "YES" ] && action

exit 0
