# Generic
export ASDF_DIR="/opt/asdf-vm"
[ -d "$ASDF_DIR" ] && source "${ASDF_DIR}/asdf.sh"

# Ruby
[ -s "$(which rbenv)" ] && eval "$(rbenv init -)"
[ -s "$(which ruby)" ] && export PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
export RUBYOPT='-W:no-deprecated -W:no-experimental'

# Python
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1
export PROJECT_HOME=$HOME/dev/python
export WORKON_HOME=$PROJECT_HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=$(which python)
export VIRTUALENVWRAPPER_VIRTUALENV=$(which virtualenv)
export VIRTUALENVWRAPPER_SCRIPT=$(which virtualenvwrapper.sh)
[ ! -d "$PROJECT_HOME" ] && mkdir -p $PROJECT_HOME
[ -s "$VIRTUALENVWRAPPER_SCRIPT" ] && source $VIRTUALENVWRAPPER_SCRIPT

# NodeJS
if [ -f /usr/share/nvm/init-nvm.sh ]; then
  source /usr/share/nvm/init-nvm.sh
  export NVM_SYMLINK_CURRENT=true
  export PATH="$HOME/.nvm/current/bin:$PATH"
fi

# Rust
[ -d "$HOME/.cargo/bin" ] && export PATH="$HOME/.cargo/bin:$PATH"

# Go
if [ -s "$(which go)" ]; then
  export GOPATH="$(go env GOPATH)"
  export PATH="$GOPATH/bin:$PATH"
fi

# .NET Core
if [ -s "$(which dotnet)" ]; then
  DOTNET_CLI_TELEMETRY_OPTOUT=1
  export PATH="/$HOME/.dotnet/tools:$PATH"
fi
