source $HOME/zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (oh-my-zsh).
antigen bundle git
antigen bundle npm
antigen bundle archlinux
antigen bundle gulp
antigen bundle laravel5
antigen bundle composer

# Other bundles not in oh-my-zsh
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
# NOTE: zsh-syntax-highlighting must be LAST!
antigen bundle zsh-users/zsh-syntax-highlighting

# Oh My ZSH settings
# Path to your oh-my-zsh installation.
export ZSH=/home/richard/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="bullet-train"
ZSH_THEME=""

# Theme settings, see https://github.com/caiogondim/bullet-train.zsh#options
# BULLETTRAIN_PROMPT_ORDER=(
  # time
  # status
  # context
  # dir
  # git
# )
# BULLETTRAIN_CONTEXT_DEFAULT_USER='richard'
# BULLETTRAIN_DIR_FG='black'
# BULLETTRAIN_NVM_FG='black'

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd-mm-yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#   NOTE: zsh-syntax-highlighting must be LAST!
#plugins=(git npm archlinux gulp laravel5 composer zsh-syntax-highlighting)

antigen apply

source $DOTFILES/zsh/aliases.zsh

