source $HOME/zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (oh-my-zsh).
antigen bundle git
antigen bundle npm
[ -f "$(which pacman)" ] && antigen bundle archlinux
[ "$PLATFORM" = "macos" ] && antigen bundle osx
antigen bundle rails
antigen bundle rbenv
antigen bundle ruby
antigen bundle django

# Other bundles not in oh-my-zsh
# NOTE: zsh-syntax-highlighting must be the LAST bundle!
antigen bundle zsh-users/zsh-syntax-highlighting

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd-mm-yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#   NOTE: zsh-syntax-highlighting must be LAST!
#plugins=(git npm archlinux gulp laravel5 composer zsh-syntax-highlighting)

# Apply antigen configs
antigen apply

source $DOTFILES/zsh/aliases.zsh

eval "$(starship init zsh)"
