source $HOME/zsh/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (oh-my-zsh).
antigen bundle git
antigen bundle npm
antigen bundle archlinux
antigen bundle rails
antigen bundle rbenv
antigen bundle ruby
antigen bundle rust

# Other bundles not in oh-my-zsh
# NOTE: zsh-syntax-highlighting must be the LAST bundle!
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme denysdovhan/spaceship-prompt

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd-mm-yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#   NOTE: zsh-syntax-highlighting must be LAST!
#plugins=(git npm archlinux gulp laravel5 composer zsh-syntax-highlighting)

###############################################################################
# Spaceship prompt options                                                    #
# https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md #
###############################################################################
# Order
SPACESHIP_PROMPT_ORDER=(
  # time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  ruby          # Ruby section
  elixir        # Elixir section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  docker        # Docker section
  venv          # virtualenv section
  pyenv         # Pyenv section
  ember         # Ember.js section
  # exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
SPACESHIP_RPROMPT_ORDER=(
  time          # Time stamps section
  exec_time     # Execution time
)
# Prompt
SPACESHIP_PROMPT_DEFAULT_PREFIX="  "
SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "
# Char
SPACESHIP_CHAR_PREFIX=""
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL="$"
# SPACESHIP_CHAR_SYMBOL="ஃ"
# SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SYMBOL_SECONDARY="❯ "
SPACESHIP_CHAR_COLOR_SECONDARY="black"
# Time (time)
SPACESHIP_TIME_SHOW=true
# Directory (dir)
SPACESHIP_DIR_PREFIX="  "
SPACESHIP_DIR_TRUNC=4
# Git (git)
SPACESHIP_GIT_PREFIX="  "
# Battery (battery)
SPACESHIP_BATTERY_SHOW=false

# Apply antigen configs
antigen apply

source $DOTFILES/zsh/aliases.zsh

[ -f /usr/share/nvm/init-nvm.sh ] && source /usr/share/nvm/init-nvm.sh
